### ISSUE TITLE
Turbine Face Collision during wallsharing.

### ISSUE THREAD

**Issue by DarkArkAngel640** [marisathewitch/Faithful32-GTCEu#2]
Hi, I am a big fan of the pack you have made and F32 in general. I would like to help begin contributing here, and this issue has bugged me for awhile and I would love to fix it! 

When wall-sharing turbines of any type, they always clip into each other like so. 
![Nomifactory (CEu version, 1 5 2, Normal Mode) 7_15_2023 10_40_49 PM](https://github.com/marisathewitch/Faithful32-GTCEu/assets/76476784/509a5edb-8d45-4f6b-b4b8-147daf2285bf)

I would like to fix this somehow. My proposed fix would be making the turbines a squared oval shape like so. 
![image](https://github.com/marisathewitch/Faithful32-GTCEu/assets/76476784/29f416ad-d561-4630-a217-eba9b8553fc1)
The turbine itself would remain circular and only need to be large enough to fill in the corners of the oval. We could also keep the mostly round shape of the face and then slightly bring in the turbine borders so that they are shared between the machines.

**Comment by marisathewitch** [comment]
Fixed in last commit
![image](https://github.com/marisathewitch/Faithful32-GTCEu/assets/5376817/56704281-08d4-495c-bc68-c49b4c59b7da)
